version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGD 1.5

# sudo docker-compose up -d     ---> create container
# sudo docker ps | grep mongo   ---> check container's status
# sudo docker stop mongo        ---> stop container
# sudo docker start mongo        ---> start container